version: '3.8'

services:
  postgres:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: ${NX_DB_NAME}
      POSTGRES_USER: ${NX_DB_USER_NAME}
      POSTGRES_PASSWORD: ${NX_DB_USER_PASSWORD}
    hostname: ${NX_DB_HOST_NAME}
    ports:
      - ${NX_DB_PORT}:${NX_DB_PORT}
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres-data:
