version: '3.8'

services:
  postgres:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    hostname: ${DB_HOST_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - .:/var/lib/postgresql/data
